// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZCK8DkDFML-FeZqyRILJqPdTEMsDt5Ok',
    appId: '1:443799814858:android:f62a0463daf1c4bb1eaa33',
    messagingSenderId: '443799814858',
    projectId: 'tripmate-bc272',
    storageBucket: 'tripmate-bc272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKG9Rq5_1awLyxxCv8j4Sf5k0YtbxOkE4',
    appId: '1:443799814858:ios:60dbecbd0b29d44c1eaa33',
    messagingSenderId: '443799814858',
    projectId: 'tripmate-bc272',
    storageBucket: 'tripmate-bc272.firebasestorage.app',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions web  = FirebaseOptions(
    apiKey: "AIzaSyD21BCmn3TywsBIoHLMNJEgS9g-Xq4DSG8",
    authDomain: "tripmate-bc272.firebaseapp.com",
    projectId: "tripmate-bc272",
    storageBucket: "tripmate-bc272.firebasestorage.app",
    messagingSenderId: "443799814858",
    appId: "1:443799814858:web:132f5af841a75d7a1eaa33"
  );
}
